
require "plugins.packer"
require "plugins.treesitter"
require "plugins.nvim_tree"
require "plugins.autopairs"
require "plugins.bar"
require "plugins.lua-line"
require "plugins.telescope"
require "plugins.lsp"
require "plugins.mas"
require "plugins.db_ui"
